global using System.ComponentModel.DataAnnotations;
global using System.ComponentModel.DataAnnotations.Schema;
global using System.Net;
global using Microsoft.EntityFrameworkCore;
global using CoreMultiLib.Model;
global using CoreMultiLib;
global using Microsoft.Extensions.Logging;
global using Microsoft.EntityFrameworkCore.Diagnostics;
global using System.Collections.Immutable;
global using EF_BeaversLife.Queries;
global using EF_BeaversLife.Extensions;

// TODO: remove
global using System;
global using System.Collections.Generic;
global using System.IO;
global using System.Linq;
global using System.Net.Http;
global using System.Threading;
global using System.Threading.Tasks;
