//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_First_Framework_Lib
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdditionalInfo
    {
        public int AdditionalInfoID { get; set; }
        public int StudentGradeId { get; set; }
    
        public virtual StudentGrade StudentGrade { get; set; }
    }
}
