//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_First_Framework_Lib
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommentTag
    {
        public int CommentId { get; set; }
        public int TagId { get; set; }
        public System.DateTime PublicationDate { get; set; }
    
        public virtual Comment Comment { get; set; }
        public virtual Tag Tag { get; set; }
    }
}
