//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_First_Framework_Lib
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_DepartmentCourseCount
    {
        public int DepartmentID { get; set; }
        public string DepartmentName { get; set; }
        public Nullable<int> CourseCount { get; set; }
    }
}
